### PR TITLE
Atomization of start/endChunkURL - Part 2

### PR DESCRIPTION
**Pull request by SingingMeerkat**

### CODE REVIEW

**Comment by josiahseaman** [comment]
Turns out < was correct.  You should never double load or double append secondJson.  Once you get that sorted we can review and merge.

**Comment by josiahseaman** [comment]
Conflicts you're seeing are from a style commit change, they should be fairly simple to resolve.

**Comment by SingingMeerkat** [comment]
All conflicts should be resolved now. I also changed back to < instead of <= when checking JSON order

**Comment by SingingMeerkat** [comment]
I went through testing procedure again, everything works as it does with the actual master. No new bug detected.

**Review by josiahseaman — CHANGES_REQUESTED** [review]
It's looking pretty good.  I was able to invoke the Visual Bug #54 after the first render, which is unusual and new to this branch.  That's not a show stopper though, since it's a preexisting condition. I'm going to make a minor change that doesn't re-processArray() if secondChunk is not new.  I like that you have a check for 
`if (this.props.store.getChunkURLs()[0] === this.props.store.getChunkURLs()[lastChunkURLIndex])` I still got a JSON parse right after that that looked like it fetched a bad file.  To reproduce: use right button to scroll to end of pangenome.  
```
Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0
Promise.then (async)		
loadFirstJSON	@	PangenomeSchematic.js:100
queueUpdate	@	App.js:85
```

image

**Pull request merged**
