### PR TITLE
#17 rendering nucleotides (updated master)

### LINKED ISSUE #17: Render nucleotides on the nearest zoom level.
Current procedure:
* Run odgi with --bin_width=1
* Rest of pipeline: segmentation produces folder with sequence stripped out
* Enter directory name for bin=1 files

What needs changed:
- [ ] ODGI needs to output a FASTA file instead of bin sequence (https://github.com/vgteam/odgi/issues/88)
- [ ] component_segmentation chunks up FASTA in parallel with component dividers
- [ ] Schematize detects small zoom level and... 
    - [ ] Read corresponding FASTA
    - [ ] renders sequence in correct position

Simplified Design

### PR DESCRIPTION
**Pull request by CrookedY**

### CODE REVIEW

**Comment by josiahseaman** [comment]
### Review Notes
* Data has switched from w100 default to w1, which is why it looks so different
* Had to overwrite data with the latest v12 json from component_segmentation
* **changes listed in branch i17_nucleotide_render**
* Height is very wrong, cutting off a lot of data
* Viz can now scroll sideways: not necessarily desirable
    * Arrows don't scroll sideways (best to just remove this)

**Comment by ChristineSeaman** [comment]
image

This displayed after scrolling bin position quite far (into the 700s).

**Comment by josiahseaman** [comment]
* Fixed loadFasta with `this.nucleotides.push(...nucleotides);`
* Nucleotides not loading from next fasta file yet, this should be derived from bin2file.json at loadIndexFile
*

**Review by josiahseaman — CHANGES_REQUESTED** [review]
Testing today shows a couple lingering issues:
* horizontal scroll is never desired, it's better that things just get clipped off the right side of the screen
* Vertical scrolling matrix is currently broken. 
    * to Test: change file to run1.B1phi1.i1.seqwish.w100 at top
    * Use scroll wheel while hovering over the matrix.  Currently does not scroll, in master it still scrolls
* It looks like mouseover events are not sent to Links, they don't turn black anymore (Step 10 in https://graph-genome.github.io//testing.html)
    * Link color still changes on linkColumn cells, that's working correctly
* Rendered nucleotides should stay frozen with arrows during vertical scrolling, currently they travel with the matrix.

Njagi is currently working on this.

**Comment by josiahseaman** [comment]
Superseded by https://github.com/graph-genome/Schematize/pull/74

**Pull request closed without merging**
