### PR TITLE
Add toggleRenderMatrix option to hide SNPs in the Matrix

### PR DESCRIPTION
**Pull request by 6br**
Issue #35 
I fixed the Schematize. Further, I found CompressedViewSwitch won't work if default is `true`. I also fixed this.

### CODE REVIEW

**Review by josiahseaman — COMMENTED** [review]
Wouldn't you need to also modify or switch renderAllConnectors?

**Comment by josiahseaman** [comment]
image

I'm not sure the spec for this quite makes sense.  The goal is likely to simplify the view.  So then shouldn't we make all component the same width?  Shouldn't connectors also be removed?  Doesn't something like a VerticalCompression rearrangement make sense as the default here?  

image
*Using Vertical Compression and thinner row size shows allele frequencies.*

The code works as is, but I think it needs more.

**Review by josiahseaman — CHANGES_REQUESTED** [review]
* Connectors
* Vertical compression
* Width compression
* Thought about any other usability improvements (path name from cell mouseover?)

**Comment by 6br** [comment]
I'm not persuaded to remove connections, because vertical compression looks enough compressed. Removing connections lose allele frequency information. However, for evaluation, I add remove connections toggle.

Here we have four options.
(1) Vertical Compression: Thin vertical size.
(2) Width Compression: Remove all matrix and adjust the same width of Component.
(2-1) Render connectors: Remove all connection.
(2-2) Width Scaling Factor: When I remove all matrix and squeezed down to one bin for each component, I figure out that each component becomes hard to see. I think each component should be wider than one bin. That's the reason I changed the scaling factor.
I'd like to reduce the number of options.

We'd need default options. My recommendation is as follows:
(A) Default: (1)disabled (2)disabled (2-1)enabled
(B) SV w/o Phasing: (1)enabled (2)enabled (2-1)enabled (2-2)3
(C) Only SV: (1)disabled (2)enabled (2-1)enabled (2-2)3

**Comment by 6br** [comment]
Default
output (10)
SV w/o Phasing
output (11)
Only SV
output (12)

**Comment by 6br** [comment]
Connector Removed

output (13)

**Comment by 6br** [comment]
Another example:

**Pull request merged**
