### PR TITLE
Style/add Eslint (#48)

### LINKED ISSUE #48: Add linting to project
#### Description

There's no linting in the project. Linting would guarantee consistency from different people who run different editors. Also, linting would ensure to catch any obvious errors. Right now I've set up this on my fork: https://npm.taobao.org/package/eslint-plugin-react and getting:

```
/home/bonface/projects/Schematize/src/App.js
   51:68   error  'store' is missing in props validation                         react/prop-types
   52:28   error  'store' is missing in props validation                         react/prop-types
   52:34   error  'store.beginEndBin' is missing in props validation             react/prop-types
   54:28   error  'store' is missing in props validation                         react/prop-types
   55:28   error  'store' is missing in props validation                         react/prop-types
   56:28   error  'store' is missing in props validation                         react/prop-types
   57:28   error  'store' is missing in props validation                         react/prop-types
   59:6    error  Unnecessary semicolon                                          no-extra-semi
   61:9    error  'console' is not defined                                       no-undef
   61:45   error  'store' is missing in props validation                         react/prop-types
   61:51   error  'store.startChunkURL' is missing in props validation           react/prop-types
   62:53   error  'store' is missing in props validation                         react/prop-types
   62:59   error  'store.startChunkURL' is missing in props validation           react/prop-types
   65:9    error  'console' is not defined                                       no-undef
   65:47   error  'store' is missing in props validation                         react/prop-types
   65:53   error  'store.startChunkURL' is missing in props validation           react/prop-types
   69:29   error  'processingDone' is assigned a value but never used            no-unused-vars
   73:13   error  'console' is not defined                                       no-undef
   86:9    error  'console' is not defined                                       no-undef
   92:51   error  'store' is missing in props validation                         react/prop-types
   92:57   error  'store.pixelsPerColumn' is missing in props validation         react/prop-types
   93:60   error  'store' is missing in props validation                         react/prop-types
   93:66   error  'store.pixelsPerColumn' is missing in props validation         react/prop-types
   99:76   error  'store' is missing in props validation                         react/prop-types
   99:82   error  'store.pixelsPerColumn' is missing in props validation         react/prop-types
   99:110  error  'store' is missing in props validation                         react/prop-types
   99:116  error  'store.topOffset' is missing in props validation               react/prop-types
  102:20   error  'store' is missing in props validation                         react/prop-types
  102:26   error  'store.updateTopOffset' is missing in props validation         react/prop-types
  110:35   error  'prevState' is defined but never used                          no-unused-vars
  110:46   error  'snapshot' is defined but never used                           no-unused-vars
  111:23   error  'store' is missing in props validation                         react/prop-types
  111:29   error  'store.getBeginBin' is missing in props validation             react/prop-types
  111:57   error  'store' is missing in props validation                         react/prop-types
  111:63   error  'store.getBeginBin' is missing in props validation             react/prop-types
  111:91   error  'store' is missing in props validation                         react/prop-types
  111:97   error  'store.getEndBin' is missing in props validation               react/prop-types
  111:123  error  'store' is missing in props validation                         react/prop-types
  111:129  error  'store.getEndBin' is missing in props validation               react/prop-types
  124:9    error  'console' is not defined                                       no-undef
  130:24   error  'store' is missing in props validation                         react/prop-types
  130:30   error  'store.useVerticalCompression' is missing in props validation  react/prop-types
  132:73   error  'store' is missing in props validation                         react/prop-types
  132:79   error  'store.pixelsPerRow' is missing in props validation            react/prop-types
  134:90   error  'store' is missing in props validation                         react/prop-types
  134:96   error  'store.pixelsPerRow' is missing in props validation            react/prop-types
  142:28   error  'document' is not defined                                      no-undef
  160:73   error  'store' is missing in props validation                         react/prop-types
  160:79   error  'store.getBeginBin' is missing in props validation             react/prop-types
  161:91   error  'store' is missing in props validation                         react/prop-types
  161:97   error  'store.pixelsPerColumn' is missing in props validation         react/prop-types
  162:52   error  'store' is missing in props validation                         react/prop-types
  162:58   error  'store.pixelsPerColumn' is missing in props validation         react/prop-types
  169:39   error  'store' is missing in props validation                         react/prop-types
  198:31   error  'store' is missing in props validation                         react/prop-types
  203:38   error  'store' is missing in props validation                         react/prop-types
  203:44   error  'store.pixelsPerRow' is missing in props validation            react/prop-types
  204:31   error  'store' is missing in props validation                         react/prop-types
  204:37   error  'store.pixelsPerColumn' is missing in props validation         react/prop-types
  213:31   error  'store' is missing in props validation                         react/prop-types
  222:9    error  'console' is not defined                                       no-undef
  225:50   error  'store' is missing in props validation                         react/prop-types
  227:35   error  'store' is missing in props validation                         react/prop-types
  227:41   error  'store.leftOffset' is missing in props validation              react/prop-types
  230:40   error  'store' is missing in props validation                         react/prop-types
  230:46   error  'store.topOffset' is missing in props validation               react/prop-types
  244:35   error  'store' is missing in props validation                         react/prop-types
  244:41   error  'store.leftOffset' is missing in props validation              react/prop-types
  245:35   error  'topOffset' is missing in props validation                     react/prop-types
  247:40   error  'store' is missing in props validation                         react/prop-types
  247:46   error  'store.topOffset' is missing in props validation               react/prop-types
  254:50   error  'store' is missing in props validation                         react/prop-types
  254:56   error  'store.topOffset' is missing in props validation               react/prop-types
  257:68   error  'i' is defined but never used                                  no-unused-vars
  262:54   error  'store' is missing in props validation                         react/prop-types

/home/bonface/projects/Schematize/src/App.test.js
  5:1   error  'it' is not defined        no-undef
  6:15  error  'document' is not defined  no-undef

/home/bonface/projects/Schematize/src/ComponentConnectorRect.js
   6:27  error  'color' is missing in props validation                           react/prop-types
  11:31  error  'x' is missing in props validation                               react/prop-types
  12:31  error  'y' is missing in props validation                               react/prop-types
  13:35  error  'width' is missing in props validation                           react/prop-types
  14:36  error  'height' is missing in props validation                          react/prop-types
  25:20  error  'store' is missing in props validation                           react/prop-types
  25:26  error  'store.updateCellTooltipContent' is missing in props validation  react/prop-types
  26:29  error  'pathName' is missing in props validation                        react/prop-types
  26:58  error  'item' is missing in props validation                            react/prop-types
  27:32  error  'item' is missing in props validation                            react/prop-types
  30:20  error  'store' is missing in props validation                           react/prop-types
  30:26  error  'store.updateCellTooltipContent' is missing in props validation  react/prop-types
  35:31  error  'x' is missing in props validation                               react/prop-types
  36:31  error  'y' is missing in props validation                               react/prop-types
  37:35  error  'width' is missing in props validation                           react/prop-types
  38:36  error  'height' is missing in props validation                          react/prop-types
  39:34  error  'color' is missing in props validation                           react/prop-types

/home/bonface/projects/Schematize/src/ComponentRect.js
   31:46  error  'i' is defined but never used                                              no-unused-vars
   56:32  error  'item' is missing in props validation                                      react/prop-types
   56:37  error  'item.matrix' is missing in props validation                               react/prop-types
   56:44  error  'item.matrix.map' is missing in props validation                           react/prop-types
   63:20  error  'store' is missing in props validation                                     react/prop-types
   63:26  error  'store.updateMaxHeight' is missing in props validation                     react/prop-types
   68:35  error  'item' is missing in props validation                                      react/prop-types
   69:30  error  'item.x' is missing in props validation                                    react/prop-types
   69:42  error  'item.arrivals' is missing in props validation                             react/prop-types
   69:51  error  'item.arrivals.length' is missing in props validation                      react/prop-types
   69:71  error  'store' is missing in props validation                                     react/prop-types
   69:77  error  'store.pixelsPerColumn' is missing in props validation                     react/prop-types
   70:38  error  'store' is missing in props validation                                     react/prop-types
   70:44  error  'store.pixelsPerColumn' is missing in props validation                     react/prop-types
   72:26  error  'store' is missing in props validation                                     react/prop-types
   72:32  error  'store.useVerticalCompression' is missing in props validation              react/prop-types
   73:29  error  'compressed_row_mapping' is missing in props validation                    react/prop-types
   73:52  error  Do not access Object.prototype method 'hasOwnProperty' from target object  no-prototype-builtins
   76:33  error  'compressed_row_mapping' is missing in props validation                    react/prop-types
   83:35  error  'store' is missing in props validation                                     react/prop-types
   84:38  error  'pathNames' is missing in props validation                                 react/prop-types
   85:43  error  'store' is missing in props validation                                     react/prop-types
   85:49  error  'store.pixelsPerColumn' is missing in props validation                     react/prop-types
   86:40  error  'store' is missing in props validation                                     react/prop-types
   86:46  error  'store.pixelsPerRow' is missing in props validation                        react/prop-types
   86:72  error  'store' is missing in props validation                                     react/prop-types
   86:78  error  'store.topOffset' is missing in props validation                           react/prop-types
   89:36  error  'store' is missing in props validation                                     react/prop-types
   89:42  error  'store.pixelsPerRow' is missing in props validation                        react/prop-types
   93:6   error  Unnecessary semicolon                                                      no-extra-semi
   96:39  error  'item' is missing in props validation                                      react/prop-types
   96:44  error  'item.departures' is missing in props validation                           react/prop-types
   97:43  error  'item.departures.slice' is missing in props validation                     react/prop-types
  102:27  error  'item.departures.length' is missing in props validation                    react/prop-types
  103:37  error  'item.departures.slice' is missing in props validation                     react/prop-types
  122:36  error  'item' is missing in props validation                                      react/prop-types
  124:33  error  'item.x' is missing in props validation                                    react/prop-types
  124:48  error  'item.firstDepartureColumn' is missing in props validation                 react/prop-types
  124:83  error  'item.departures' is missing in props validation                           react/prop-types
  124:94  error  'item.departures.length' is missing in props validation                    react/prop-types
  125:24  error  'store' is missing in props validation                                     react/prop-types
  125:30  error  'store.pixelsPerColumn' is missing in props validation                     react/prop-types
  127:26  error  'store' is missing in props validation                                     react/prop-types
  127:32  error  'store.useVerticalCompression' is missing in props validation              react/prop-types
  128:33  error  'compressed_row_mapping' is missing in props validation                    react/prop-types
  133:27  error  'store' is missing in props validation                                     react/prop-types
  133:33  error  'store.topOffset' is missing in props validation                           react/prop-types
  133:65  error  'store' is missing in props validation                                     react/prop-types
  133:71  error  'store.pixelsPerRow' is missing in props validation                        react/prop-types
  134:31  error  'store' is missing in props validation                                     react/prop-types
  134:37  error  'store.pixelsPerColumn' is missing in props validation                     react/prop-types
  135:32  error  'store' is missing in props validation                                     react/prop-types
  135:38  error  'store.pixelsPerRow' is missing in props validation                        react/prop-types
  144:35  error  'item' is missing in props validation                                      react/prop-types
  144:40  error  'item.x' is missing in props validation                                    react/prop-types
  145:35  error  'store' is missing in props validation                                     react/prop-types
  145:41  error  'store.topOffset' is missing in props validation                           react/prop-types
  146:39  error  'width' is missing in props validation                                     react/prop-types
  146:58  error  'store' is missing in props validation                                     react/prop-types
  146:64  error  'store.pixelsPerColumn' is missing in props validation                     react/prop-types
  147:40  error  'height' is missing in props validation                                    react/prop-types
  147:60  error  'store' is missing in props validation                                     react/prop-types
  147:66  error  'store.pixelsPerRow' is missing in props validation                        react/prop-types

/home/bonface/projects/Schematize/src/ControlHeader.js
    7:37   error  'store' is missing in props validation                               react/prop-types
    7:43   error  'store.getBeginBin' is missing in props validation                   react/prop-types
    8:35   error  'store' is missing in props validation                               react/prop-types
    8:41   error  'store.getEndBin' is missing in props validation                     react/prop-types
   11:9    error  'console' is not defined                                             no-undef
   12:20   error  'store' is missing in props validation                               react/prop-types
   12:26   error  'store.updateBeginEndBin' is missing in props validation             react/prop-types
   17:9    error  'console' is not defined                                             no-undef
   17:54   error  'store' is missing in props validation                               react/prop-types
   17:60   error  'store.getPath' is missing in props validation                       react/prop-types
   17:110  error  'store' is missing in props validation                               react/prop-types
   17:116  error  'store.getNucPos' is missing in props validation                     react/prop-types
   20:34   error  'store' is missing in props validation                               react/prop-types
   21:28   error  'store.pathIndexServerAddress' is missing in props validation        react/prop-types
   22:33   error  'store.getPath' is missing in props validation                       react/prop-types
   23:31   error  'store.getNucPos' is missing in props validation                     react/prop-types
   24:32   error  'store.binWidth' is missing in props validation                      react/prop-types
   28:17   error  'alert' is not defined                                               no-undef
   30:17   error  'console' is not defined                                             no-undef
   34:17   error  'console' is not defined                                             no-undef
   35:23   error  'store.updateBeginEndBin' is missing in props validation             react/prop-types
   35:60   error  'store.getEndBin' is missing in props validation                     react/prop-types
   48:57   error  'store' is missing in props validation                               react/prop-types
   48:63   error  'store.jsonName' is missing in props validation                      react/prop-types
   49:38   error  'store' is missing in props validation                               react/prop-types
   49:44   error  'store.tryJSONpath' is missing in props validation                   react/prop-types
   59:56   error  'store' is missing in props validation                               react/prop-types
   59:62   error  'store.beginEndBin' is missing in props validation                   react/prop-types
   60:54   error  'store' is missing in props validation                               react/prop-types
   60:60   error  'store.updateBeginEndBin' is missing in props validation             react/prop-types
   60:109  error  'store' is missing in props validation                               react/prop-types
   60:115  error  'store.getEndBin' is missing in props validation                     react/prop-types
   62:56   error  'store' is missing in props validation                               react/prop-types
   62:62   error  'store.beginEndBin' is missing in props validation                   react/prop-types
   63:54   error  'store' is missing in props validation                               react/prop-types
   63:60   error  'store.updateBeginEndBin' is missing in props validation             react/prop-types
   63:89   error  'store' is missing in props validation                               react/prop-types
   63:95   error  'store.getBeginBin' is missing in props validation                   react/prop-types
   77:54   error  'store' is missing in props validation                               react/prop-types
   77:60   error  'store.updatePathNucPos' is missing in props validation              react/prop-types
   77:108  error  'store' is missing in props validation                               react/prop-types
   77:114  error  'store.getNucPos' is missing in props validation                     react/prop-types
   83:54   error  'store' is missing in props validation                               react/prop-types
   83:60   error  'store.updatePathNucPos' is missing in props validation              react/prop-types
   83:88   error  'store' is missing in props validation                               react/prop-types
   83:94   error  'store.getPath' is missing in props validation                       react/prop-types
   93:61   error  'store' is missing in props validation                               react/prop-types
   96:68   error  'store' is missing in props validation                               react/prop-types
   96:74   error  'store.pixelsPerRow' is missing in props validation                  react/prop-types
   97:49   error  'store' is missing in props validation                               react/prop-types
   97:55   error  'store.updateHeight' is missing in props validation                  react/prop-types
  100:68   error  'store' is missing in props validation                               react/prop-types
  100:74   error  'store.pixelsPerColumn' is missing in props validation               react/prop-types
  101:49   error  'store' is missing in props validation                               react/prop-types
  101:55   error  'store.updateWidth' is missing in props validation                   react/prop-types
  114:52   error  'store' is missing in props validation                               react/prop-types
  114:58   error  'store.useVerticalCompression' is missing in props validation        react/prop-types
  115:38   error  'store' is missing in props validation                               react/prop-types
  115:44   error  'store.toggleUseVerticalCompression' is missing in props validation  react/prop-types

/home/bonface/projects/Schematize/src/LinkArrow.js
   17:24   error  'prevProps' is defined but never used                        no-unused-vars
   17:35   error  'prevState' is defined but never used                        no-unused-vars
   17:46   error  'snapshot' is defined but never used                         no-unused-vars
   26:31   error  'link' is missing in props validation                        react/prop-types
   27:39   error  'link' is missing in props validation                        react/prop-types
   27:44   error  'link.xArrival' is missing in props validation               react/prop-types
   28:40   error  'link' is missing in props validation                        react/prop-types
   28:45   error  'link.xDepart' is missing in props validation                react/prop-types
   30:72   error  'store' is missing in props validation                       react/prop-types
   30:78   error  'store.pixelsPerColumn' is missing in props validation       react/prop-types
   31:31   error  'store' is missing in props validation                       react/prop-types
   31:37   error  'store.pixelsPerColumn' is missing in props validation       react/prop-types
   34:54   error  'store' is missing in props validation                       react/prop-types
   34:60   error  'store.pixelsPerColumn' is missing in props validation       react/prop-types
   35:65   error  'link.elevation' is missing in props validation              react/prop-types
   36:64   error  'link.elevation' is missing in props validation              react/prop-types
   37:56   error  'link.elevation' is missing in props validation              react/prop-types
   38:57   error  'link.elevation' is missing in props validation              react/prop-types
   48:48   error  'store' is missing in props validation                       react/prop-types
   48:54   error  'store.pixelsPerColumn' is missing in props validation       react/prop-types
   49:21   error  'link.isArrival' is missing in props validation              react/prop-types
   55:58   error  'store' is missing in props validation                       react/prop-types
   55:64   error  'store.pixelsPerColumn' is missing in props validation       react/prop-types
   61:13   error  'console' is not defined                                     no-undef
   75:31   error  'store' is missing in props validation                       react/prop-types
   75:37   error  'store.topOffset' is missing in props validation             react/prop-types
   76:35   error  'store' is missing in props validation                       react/prop-types
   76:41   error  'store.pixelsPerColumn' is missing in props validation       react/prop-types
   79:41   error  'store' is missing in props validation                       react/prop-types
   79:47   error  'store.pixelsPerColumn' is missing in props validation       react/prop-types
   80:34   error  'color' is missing in props validation                       react/prop-types
   81:36   error  'color' is missing in props validation                       react/prop-types
   94:20   error  'updateHighlightedNode' is missing in props validation       react/prop-types
   94:53   error  'link' is missing in props validation                        react/prop-types
   94:58   error  'link.linkColumn' is missing in props validation             react/prop-types
   97:20   error  'updateHighlightedNode' is missing in props validation       react/prop-types
  102:9    error  'console' is not defined                                     no-undef
  102:48   error  'link' is missing in props validation                        react/prop-types
  104:32   error  'store' is missing in props validation                       react/prop-types
  104:38   error  'store.getEndBin' is missing in props validation             react/prop-types
  104:63   error  'store' is missing in props validation                       react/prop-types
  104:69   error  'store.getBeginBin' is missing in props validation           react/prop-types
  105:34   error  'store' is missing in props validation                       react/prop-types
  105:40   error  'store.getBeginBin' is missing in props validation           react/prop-types
  107:46   error  'link' is missing in props validation                        react/prop-types
  107:51   error  'link.linkColumn' is missing in props validation             react/prop-types
  107:62   error  'link.linkColumn.upstream' is missing in props validation    react/prop-types
  108:33   error  'link' is missing in props validation                        react/prop-types
  108:38   error  'link.linkColumn' is missing in props validation             react/prop-types
  108:49   error  'link.linkColumn.downstream' is missing in props validation  react/prop-types
  110:55   error  'link' is missing in props validation                        react/prop-types
  110:60   error  'link.linkColumn' is missing in props validation             react/prop-types
  110:71   error  'link.linkColumn.downstream' is missing in props validation  react/prop-types
  110:95   error  'link' is missing in props validation                        react/prop-types
  110:100  error  'link.linkColumn' is missing in props validation             react/prop-types
  110:111  error  'link.linkColumn.upstream' is missing in props validation    react/prop-types
  113:20   error  'store' is missing in props validation                       react/prop-types
  113:26   error  'store.updateBeginEndBin' is missing in props validation     react/prop-types

/home/bonface/projects/Schematize/src/LinkColumn.js
  12:20  error  'updateHighlightedNode' is missing in props validation                     react/prop-types
  12:53  error  'item' is missing in props validation                                      react/prop-types
  15:20  error  'updateHighlightedNode' is missing in props validation                     react/prop-types
  20:48  error  'item' is missing in props validation                                      react/prop-types
  20:53  error  'item.participants' is missing in props validation                         react/prop-types
  20:66  error  'item.participants.entries' is missing in props validation                 react/prop-types
  23:34  error  'store' is missing in props validation                                     react/prop-types
  23:40  error  'store.useVerticalCompression' is missing in props validation              react/prop-types
  24:38  error  'compressed_row_mapping' is missing in props validation                    react/prop-types
  24:61  error  Do not access Object.prototype method 'hasOwnProperty' from target object  no-prototype-builtins
  27:41  error  'compressed_row_mapping' is missing in props validation                    react/prop-types
  29:47  error  'store' is missing in props validation                                     react/prop-types
  29:53  error  'store.pixelsPerRow' is missing in props validation                        react/prop-types
  37:31  error  'color' is missing in props validation                                     react/prop-types
  47:39  error  'x' is missing in props validation                                         react/prop-types
  48:39  error  'store' is missing in props validation                                     react/prop-types
  48:45  error  'store.topOffset' is missing in props validation                           react/prop-types
  49:43  error  'store' is missing in props validation                                     react/prop-types
  49:49  error  'store.pixelsPerColumn' is missing in props validation                     react/prop-types
  50:44  error  'store' is missing in props validation                                     react/prop-types
  50:50  error  'store.pixelsPerRow' is missing in props validation                        react/prop-types
  51:42  error  'color' is missing in props validation                                     react/prop-types

/home/bonface/projects/Schematize/src/LinkRecord.js
   5:13  error  'console' is not defined  no-undef
  88:13  error  'console' is not defined  no-undef

/home/bonface/projects/Schematize/src/NucleotideTooltip.js
  20:52  error  'store' is missing in props validation                     react/prop-types
  20:58  error  'store.cellToolTipContent' is missing in props validation  react/prop-types

/home/bonface/projects/Schematize/src/PangenomeSchematic.js
   13:33  error  'store' is missing in props validation                    react/prop-types
   13:39  error  'store.jsonName' is missing in props validation           react/prop-types
   14:37  error  'store' is missing in props validation                    react/prop-types
   14:43  error  'store.startChunkURL' is missing in props validation      react/prop-types
   16:22  error  'store' is missing in props validation                    react/prop-types
   17:34  error  'store' is missing in props validation                    react/prop-types
   17:40  error  'store.jsonName' is missing in props validation           react/prop-types
   25:31  error  'store' is missing in props validation                    react/prop-types
   25:37  error  'store.getBeginBin' is missing in props validation        react/prop-types
   26:29  error  'store' is missing in props validation                    react/prop-types
   26:35  error  'store.getEndBin' is missing in props validation          react/prop-types
   36:5   error  'console' is not defined                                  no-undef
   38:16  error  'store' is missing in props validation                    react/prop-types
   38:22  error  'store.updateBeginEndBin' is missing in props validation  react/prop-types
   44:14  error  'store' is missing in props validation                    react/prop-types
   44:20  error  'store.switchChunkFiles' is missing in props validation   react/prop-types
   45:4   error  'process' is not defined                                  no-undef
   45:55  error  'store' is missing in props validation                    react/prop-types
   45:61  error  'store.jsonName' is missing in props validation           react/prop-types
   46:4   error  'process' is not defined                                  no-undef
   46:55  error  'store' is missing in props validation                    react/prop-types
   46:61  error  'store.jsonName' is missing in props validation           react/prop-types
   49:19  error  'process' is not defined                                  no-undef
   50:3   error  'console' is not defined                                  no-undef
   52:4   error  'alert' is not defined                                    no-undef
   56:3   error  'console' is not defined                                  no-undef
   57:18  error  'XMLHttpRequest' is not defined                           no-undef
   60:20  error  'process' is not defined                                  no-undef
   73:17  error  'store' is missing in props validation                    react/prop-types
   73:23  error  'store.startChunkURL' is missing in props validation      react/prop-types
   73:52  error  'store' is missing in props validation                    react/prop-types
   73:58  error  'store.endChunkURL' is missing in props validation        react/prop-types
   76:38  error  'store' is missing in props validation                    react/prop-types
   76:44  error  'store.endChunkURL' is missing in props validation        react/prop-types
   85:4   error  'console' is not defined                                  no-undef
   94:40  error  'store' is missing in props validation                    react/prop-types
   94:46  error  'store.getBeginBin' is missing in props validation        react/prop-types
   94:72  error  'store' is missing in props validation                    react/prop-types
   94:78  error  'store.getEndBin' is missing in props validation          react/prop-types
   95:2   error  Mixed spaces and tabs                                     no-mixed-spaces-and-tabs
   96:2   error  Mixed spaces and tabs                                     no-mixed-spaces-and-tabs
   96:16  error  'MediaError' is not defined                               no-undef
  101:2   error  Mixed spaces and tabs                                     no-mixed-spaces-and-tabs
  101:17  error  'store' is missing in props validation                    react/prop-types
  101:23  error  'store.setBinWidth' is missing in props validation        react/prop-types
  102:3   error  'console' is not defined                                  no-undef
  123:4   error  'console' is not defined                                  no-undef
  165:3   error  Unnecessary semicolon                                     no-extra-semi

/home/bonface/projects/Schematize/src/URL.js
   8:22  error  'XMLHttpRequest' is not defined  no-undef
   9:27  error  'process' is not defined         no-undef
  16:23  error  'XMLHttpRequest' is not defined  no-undef

/home/bonface/projects/Schematize/src/ViewportInputsStore.js
   44:13  error  'console' is not defined          no-undef
   45:13  error  'console' is not defined          no-undef
   74:25  error  'process' is not defined          no-undef
  136:12  error  'self' is defined but never used  no-unused-vars

/home/bonface/projects/Schematize/src/index.js
  8:39  error  'document' is not defined  no-undef
```

### PR DESCRIPTION
**Pull request by BonfaceKilz**
#### Description
- Add basic linting to the project. The configs are found [here](https://github.com/graph-genome/Schematize/blob/e272d6f7dc1acfd224d866e3467ed2706cb5c112/.eslintrc.json)
- Lint most of the files (closes #48)
- Update docs to contain linting section
- Remove `./src/App.test.js`. This does no useful testing IMHO. I'd suggest we create a separate issue to add some tests

#### How should this be tested?
- Run `npm install` to get the latest devdependencies
- Run `npm run lint` to run the linter

Right now, linting errors are only reduced to: 
```
/home/bonface/projects/Schematize/src/App.js
  252:68  error  'i' is defined but never used  no-unused-vars

/home/bonface/projects/Schematize/src/ComponentRect.js
  75:52  error  Do not access Object.prototype method 'hasOwnProperty' from target object  no-prototype-builtins

/home/bonface/projects/Schematize/src/LinkColumn.js
  24:61  error  Do not access Object.prototype method 'hasOwnProperty' from target object  no-prototype-builtins

/home/bonface/projects/Schematize/src/ViewportInputsStore.js
  136:12  error  'self' is defined but never used  no-unused-vars


```
#### Any background context you want to provide?
- This was driven by the motivation of making things consistent after seeing tabs and spaces, camelCase and snake_case in the same project

#### Screenshot if Appropriate
N/A

#### Questions
N/A

### CODE REVIEW

**Comment by BonfaceKilz** [comment]
I'll add the Google Style to Eslint sometime tomorrow.

**Comment by BonfaceKilz** [comment]
After adding an integration with esilnt and prettier, I've refrained from committing style fixes since those can be made later.

**Comment by ChristineSeaman** [comment]
I went through testing and wanted to share my notes. These may be known issues, but figured I'd add the results in one place. All in all, it looks really good.

* Issue: Changed the path position to "262" : 120 and click jump re-rendered. Vast majority of information disappeared from the matrix, but seemed to stack up on top of themselves on the left hand of the screen. If the user clicks on the columns that are displaying then they start populating the matrix one column at a time. Screen shots below.
* When testing that the cells in the matrix match the color of their corresponding arrow, at least one link in the green section did not have any related cells displayed. Activating the Vertical Compression then displays a single middle green cells/row at the top. It is possible that some of the information is not displaying at the bottom of the screen scroll in the default views.
* When mouse-overing the cells (grey blocks) it displays the cell coordinates, but not the corresponding labels (e.g. Coverage, Inversion).

Capture

**Comment by josiahseaman** [comment]
@BonfaceKilz These identified issues are going to be broken into a separate issue, not this PR.  Please handle the merge with the latest master and we'll merge in all the linting.  Then we can also do a big style update commit.  Thanks!

**Comment by BonfaceKilz** [comment]
@josiahseaman I've fixed the merge conflicts, you can have a look. Most of the changes are white space changes. Now it'd be the responsibility of individual authors to fix any lint errors generated from Eslint. Once we get everything working, I could set up travis or circleCI to automatically check linting on every PR, but IMHO, we are better.

**Comment by BonfaceKilz** [comment]
Let me know if there's anything off. I could always revert things affected, but I highly doubt it.

**Comment by josiahseaman** [comment]
Have you run a basic user test on the merge?  If so I'm happy to merge it now. I'm away from my computer.

**Comment by BonfaceKilz** [comment]
@josiahseaman Yes I have.

**Pull request merged**
