### PR TITLE
Handling arrays of chunk URLs

### PR DESCRIPTION
**Pull request by SingingMeerkat**
Worked based on issue #22 , I tried to fulfill most of the last to do checkboxes.

loadFirstJSON now call loadRestJSON instead of loadSecondJSON when there is more than one URL within this.chunkURLs.

Improvement could be achieved by calling processArray only once all chunks are loaded. I had a hard time trying to see how this could get done but as fetch is a promise I do not really know how to handle that.
Also it happens that loadFirstJSON is called twice from different promises at the almost same time, which causes the error "Chunk was already loaded.  Check the order you set store.chunkURLs" (first asynchronous function already sets this.jsonData.last_bin, overlaps with second asynchronous function which raises the error). At least that's what I understood of it.

### CODE REVIEW

**Comment by SingingMeerkat** [comment]
I am checking what the conflicts are right now

**Comment by josiahseaman** [comment]
I just started continuing work on this feature in branch: i22_chunk_URL_array.  Currently working on:
* rewrite loadSecondJson to work with an array

**Review by josiahseaman — CHANGES_REQUESTED** [review]
This issue is more challenging than it first appears.  The current code state doesn't have any handling for loading more than one chunk.  I've written the full technical spec here: https://github.com/graph-genome/Schematize/issues/22
If Eloi is unavailable, we'll need a new volunteer to continue this issue.

**Comment by josiahseaman** [comment]
@SingingMeerkat If you are going to continue development, make sure to check out `i22_chunk_URL_array` branch.  I've added some significant changes to the state model.  It's working satisfactory so far.  The next step is to make sure PangenomeSchematic object get pre-render information currently coming from App.updateSchematicMetadata()

**Comment by josiahseaman** [comment]
This PR was superseded by https://github.com/graph-genome/Schematize/pull/73

**Pull request closed without merging**
