### PR TITLE
Fix CORS issues #38

### LINKED ISSUE #38: Need for smarter chunk filename finding: CORS or SyntaxError: JSON.parse or FileNotFound
A fresh master clone fails with
```
`SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`
```
For the full error go to http://193.196.29.55:3000/.

### PR DESCRIPTION
**Pull request by jacobwindsor**
Consider this a WIP as more can be done but this fixes issues mentioned in #38

## Work done
- Now use [fetch api](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) instead of xhr/$.JSON
- Removes default values in the store for start and end chunks
- Gets the initial values from the bin2file.json
- No more synchronous requests
- Added rudimentary loading indicator to App.js

## Considerations
I'm adding a few considerations since I didn't have much time to get rid of all of that "hacky" feeling.

- You will see a console error for "second chunk was earlier than first". I've left the error message but not sure this is actually an issue. If you confirm this is not an issue, I will remove the console output, or if it is, then i'll fix.
- Should be a bit more robust but there's still a few code smells. e.g:
  - (my bad) I think the initial state for start/endChunkURL should come from one level higher. I think the call to bin2file.json should come from the component one level up in the tree. Either in its constructor or in `getDerivedState` (I don't know which).
  - presence of `loadFirstJson` and `loadSecondJson` could be made into one function (they essentially do the same thing). Can detect if is first or last from the app state

### CODE REVIEW

**Comment by josiahseaman** [comment]
This is good work and it really sounds like you know what you're doing.  **Jacob, Please merge in the latest from master.** Hannah Sewell finished a PR (this is good news) that also affects App.js in a fairly straightforward way.  She moved the Link display to a second < Layer >. 
* "second chunk was earlier than first": not a timing issue except that processArray() can't proceed until both files have arrived.  This is due to the need to calculate cumulative X offset.
* presence of `loadFirstJson` and `loadSecondJson` could be made into one function: I'm agnostic.  They're thin functions.
* `getDerivedState`: I don't know enough about this design pattern to comment.  Perhaps it's best to hold off on a further refactor until we decide if a list of chunks may be necessary (I'm leaning towards yes) as I mentioned here:

> **For extra credit:** We may eventually want to read in more than two chunks at a time.  If mobx could take a list of chunk filenames, that would allow us more spanning.  However I avoided coding this at first because it get complicated and mobx.arrays are a pain.  I recommend making the current startChunkURL and endChunkURL more robust first before attempting to replace them entirely.  That can be a separate issue following on #22.

**Comment by jacobwindsor** [comment]
For the first bullet point, I think that issue is fixed since I used promises. It's assured that the first file can't arrive after the second

**Comment by jacobwindsor** [comment]
Oh and forgot to mention about polyfills. I don't know what browsers you're targeting but fetch is fairly modern. As far as I'm aware, create react app polyfills it for you but I could be wrong

**Comment by josiahseaman** [comment]
Thanks for updating with Hannah's content.  We'll get this reviewed today.

**Comment by josiahseaman** [comment]
Thanks Jacob, I really like the style of code changes you made.  It'll be great to be rid of jQuery.  Just one more thing.  This appears to introduce a state bug in the leftOffset under some circumstances.  
To reproduce:
1. Start with a fresh page
2. Mouse over a colored cell in a link column 
3. Observed: Matrix jumps to the left but the arrows and link columns do not move.

Here's a video of the bug:
https://drive.google.com/open?id=1fs4NMysLUG_LYnxbA0RPl9PNLJKd2H_r

**Comment by josiahseaman** [comment]
I've verified this bug exists in 05d5b52d45ff2ee629dbad1c2e7f45768cce0db3, so it doesn't have to do with CrookedY's changes being merged.  I wasn't able to find the state change that causing the bad render, but you might find the React Profiler helpful for locating the variable change event: https://reactjs.org/blog/2018/09/10/introducing-the-react-profiler.html#browsing-commits

**Comment by jacobwindsor** [comment]
JavaScript is stylish! 

I'll have a look at it later on today or tomorrow. Thanks for verifying it's my change that made the problem.

**Comment by josiahseaman** [comment]
I really want to merge your changes, but we can't until the render bug is tracked down for the sake of following procedure.  It's also possible your change simply exposed an underlying race condition, which is why I was trying to get a history of React state "commits".  Something like rendering a component before leftOffset gets calculated would cause this problem.

**Comment by jacobwindsor** [comment]
It's a wise procedure. Unfortunately, I'm away from my computer at the moment.

Okay that's good to know and probably quite likely. I can't see anything obvious in my commits that would have caused this. 

If it's urgent, feel free to push to my repo, I can give you rights.

**Comment by Mark-Seaman** [comment]
Thank you for submitting this pull request.

After merging with the recent updates to master 9dd54119a57d9457f420909de03631301b03de4a
we merged in your changes

```
git checkout -b jacobwindsor-master master\ngit pull https://github.com/jacobwindsor/Schematize.git master\n
git branch
```

Testing was done with https://graph-genome.github.io/testing.

During step 10 we encountered an issue.  To reproduce this bug do the following.

* Refresh the view
* When mousing over the Links the screen does not refresh properly.

image
 
We will wait to merge this PR #46 until this can be fixed.

Issue does not exist in 9dd54119a57d9457f420909de03631301b03de4a

**Comment by subwaystation** [comment]
@jacobwindsor A fresh `npm start` and everything works fine. But hitting `F5` and hovering over a link breaks the application as displayed above. The moment I click to show me the next part of the pangenome, this does not occur again. Maybe some states are not resolved properly?

**Review by josiahseaman — CHANGES_REQUESTED** [review]
I was able to reproduce the bug from Mark and Simon.  Since it's important to merge this in soon, I'm going to try my hand at debugging.

**Comment by josiahseaman** [comment]
Based on [testing results from Christine](https://github.com/graph-genome/Schematize/pull/49#issuecomment-609968036), we've determined the weird render state isn't specific to this PR.  It's a state inconsistency that's possible to access from several different avenues. So Jacob didn't introduce this.  We'll merge this PR and open 2 new issues based on Christine's testing.

**Pull request merged**
